config/urls.py
from django.contrib import admin # type: ignore
from django.urls import path, include # type: ignore
from django.conf import settings # type: ignore
from django.conf.urls.static import static # type: ignore

urlpatterns = [
    path("management/", admin.site.urls),
    path('', include('expenses_mate.urls')),
    path('accounts/', include('allauth.urls'))
]

expenses_mate/urls.py
from django.urls import path # type: ignore
from .views import *
from django.contrib.auth import views as auth_views # type: ignore

app_name = 'expenses_mate'

urlpatterns = [
    # path('', ExpenseListView.as_view(), name="expenses_group_list"),
    path('account/login/', auth_views.LoginView.as_view(template_name='account/login.html'), name='account_login'),
    path('', ExpenseGroupListCreateView.as_view(), name='expenses_list_create'),
    path('expenses/<int:group_id>/', ExpenseManageView.as_view(), name='expense_detail'),
    path('updateExpensesList/<int:group_id>/', UpdateExpenseGroupView.as_view(), name='update_expense_group'),
    path('share/<int:group_id>/', ShareExpenseGroupView.as_view(), name='share_expense_group'),
    path('updateExpense<int:expense_id>/', UpdateExpenseView.as_view(), name='update_expense'),
]

expenses_mate/models.py
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin # type: ignore
from django.db import models # type: ignore


class UserManager(BaseUserManager):
    def create_user(self, email, password=None, **extra_fields):
        if not email:
            raise ValueError("The Email field must be set")
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)  # Hash the password
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        return self.create_user(email, password, **extra_fields)
    

class User(AbstractBaseUser, PermissionsMixin):
    class Meta:
        db_table = "User"
        verbose_name = "ユーザー"
        verbose_name_plural = "ユーザー"

    user_id = models.AutoField(primary_key=True)
    username = models.CharField(max_length=100, unique=True)
    email = models.EmailField(max_length=255, unique=True)
    password = models.CharField(max_length=255)
    
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)

    objects = UserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    def __str__(self):
        return self.username


class ExpenseGroup(models.Model):
    class Meta:
        db_table = "ExpenseGroup"
        verbose_name = "支出グループ"
        verbose_name_plural = "支出グループ"

    group_id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=100)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    shared_with = models.ManyToManyField(User, related_name='shared_expense_groups', blank=True)

    def __str__(self):
        return self.title

class Expense(models.Model):
    class Meta:
        db_table = "Expense"
        verbose_name = "費用"
        verbose_name_plural = "費用"

    expense_id = models.AutoField(primary_key=True)
    group_id = models.ForeignKey(ExpenseGroup, on_delete=models.CASCADE)
    user_id = models.ForeignKey(User, on_delete=models.CASCADE)
    item_name = models.CharField(max_length=100)
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    # transaction_type = models.CharField(max_length=10, choices=[('add', 'Add'), ('subtract', 'Subtract'),
    #                                                             ('multiply', 'Multiply'), ('divide', 'Divide')])
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.item_name

expenses_mate/forms.py
from django import forms # type: ignore
from .models import ExpenseGroup, Expense, User


class ExpenseGroupForm(forms.ModelForm):
    """
    新規データ登録画面用のフォーム定義
    """
    shared_with = forms.ModelMultipleChoiceField(
        queryset=User.objects.all(),  # You can filter if necessary
        widget=forms.SelectMultiple(attrs={
            'class': 'expenses-list-input',
            'id': 'input__shared_with'
        }),
        required=False  # Makes this field optional
    )
    
    class Meta:
        model = ExpenseGroup
        fields =['title', 'shared_with']
        
    def __init__(self, *args, **kwargs):
        super(ExpenseGroupForm, self).__init__(*args, **kwargs)
        self.fields['title'].widget.attrs.update({
            'class': 'expenses-list-input',
            'placeholder': ' ',
            'id': 'input__username'
        })
        

class ExpenseForm(forms.ModelForm):
    class Meta:
        model = Expense
        fields = ['item_name', 'amount']
        
    def __init__(self, *args, **kwargs):
        super(ExpenseForm, self).__init__(*args, **kwargs)
        self.fields['item_name'].widget.attrs.update({
            'class': 'expenses-list-input',
            'placeholder': ' ',
            'id': 'input__item_name'
        })
        
        self.fields['amount'].widget.attrs.update({
            'class': 'expenses-list-input',
            'placeholder': ' ',
            'id': 'input__amount'
        })

expenses_mate/views.py
from django.db import models # type: ignore
from django.views.generic import View, ListView, FormView, UpdateView# type: ignore
from django.shortcuts import render, redirect # type: ignore
from django.urls import reverse_lazy # type: ignore
from django.db.models import Sum # type: ignore
from .models import User, ExpenseGroup, Expense
from django.contrib.auth.mixins import LoginRequiredMixin # type: ignore
from .forms import ExpenseGroupForm, ExpenseForm # type: ignore
from django.db.models import Q # type: ignore
from django.shortcuts import get_object_or_404 # type: ignore

class ExpenseGroupListCreateView(LoginRequiredMixin, View):
    template_name = 'expenses_mate/expenses_list.html'
    
    def get(self, request, *args, **kwargs):
        expense_groups = ExpenseGroup.objects.filter(
            Q(created_by=request.user) | Q(shared_with=request.user)
        ).select_related('created_by').annotate(
            total_expense=Sum('expense__amount', output_field=models.DecimalField())
        )
        all_users = User.objects.all()
        form = ExpenseGroupForm()
        context = {
            'expenses_group': expense_groups,
            'form': form,
            'all_users': all_users
        }
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        if 'delete_id' in request.POST:
            # Handle deletion of an expense group
            expense_group = get_object_or_404(ExpenseGroup, group_id=request.POST['delete_id'], created_by=request.user)
            expense_group.delete()
            return redirect('expenses_mate:expenses_list_create')  # Redirect after deletion
        
        form = ExpenseGroupForm(request.POST)
        if form.is_valid():
            expense_group = form.save(commit=False)
            expense_group.created_by = request.user
            expense_group.save()
            form.save_m2m() 
            return redirect('expenses_mate:expenses_list_create') 
        
        expense_groups = ExpenseGroup.objects.filter(
            Q(created_by=request.user) | Q(shared_with=request.user)
        ).select_related('created_by').annotate(
            total_expense=Sum('expense__amount', output_field=models.DecimalField())
        )
        all_users = User.objects.all()
        context = {
            'expenses_group': expense_groups,
            'form': form,
            'all_users': all_users,
        }
        return render(request, self.template_name, context)

# class ExpenseDetailView(LoginRequiredMixin, View):
#     model = Expense
#     template_name = 'expenses_mate/expenses_detail.html'
#     login_url = 'expenses_mate:account_login'

#     def get(self, request, *args, **kwargs):
#         group_id = self.kwargs.get('group_id')
#         group = get_object_or_404(ExpenseGroup, group_id=group_id)
#         expenses = self.get_queryset(group)

#         user_totals = self.calculate_user_totals(group)

#         context = {
#             'expenses': expenses,
#             'user_totals': user_totals,
#             'form': ExpenseForm(),
#             'expenses_group': group
#         }
#         return render(request, self.template_name, context)

#     def get_queryset(self, group):
#         return Expense.objects.filter(group_id=group)

#     def calculate_user_totals(self, group):
#         return (
#             Expense.objects.filter(group_id=group)
#             .values('user_id__username')
#             .annotate(total_amount=Sum('amount'))
#             .order_by('user_id__username')
#         )

#     def post(self, request, *args, **kwargs):
#         group_id = self.kwargs.get('group_id')
#         group = get_object_or_404(ExpenseGroup, group_id=group_id) 
#         form = ExpenseForm(request.POST)
#         if form.is_valid():
#             expense = form.save(commit=False)
#             expense.group_id = group
#             expense.user_id = request.user
#             expense.save()
#             return redirect('expenses_mate:expense_detail', group_id=group_id)

#         expenses = self.get_queryset(group)
#         user_totals = self.calculate_user_totals(group)
#         context = {
#             'expenses': expenses,
#             'user_totals': user_totals,
#             'form': form,
#         }
#         return render(request, self.template_name, context)
    
class ExpenseManageView(LoginRequiredMixin, FormView, ListView):
    template_name = 'expenses_mate/expenses_detail.html'
    form_class = ExpenseForm
    model = Expense
    context_object_name = 'expenses'

    def get_success_url(self):
        return reverse_lazy('expenses_mate:expense_detail', kwargs={'group_id': self.kwargs['group_id']})

    def get_queryset(self):
        group_id = self.kwargs['group_id']
        return Expense.objects.filter(group_id=group_id)

    def get_form(self):
        form = super().get_form()
        form.instance.user_id = self.request.user
        return form

    def form_valid(self, form):
        group_id = self.kwargs['group_id']
        form.instance.group_id = get_object_or_404(ExpenseGroup, group_id=group_id)
        form.instance.user_id = self.request.user
        form.save()
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        group_id = self.kwargs['group_id']
        context['expenses'] = self.get_queryset()  # Set for ListView
        context['expenses_group'] = get_object_or_404(ExpenseGroup, group_id=group_id)
        context['user_totals'] = (
            Expense.objects.filter(group_id=group_id)
                .values('user_id__username')
                .annotate(total_amount=Sum('amount'))
                .order_by('user_id__username')
        )
        context['form'] = self.get_form()  # Add form for FormView
        return context

    def post(self, request, *args, **kwargs):
        if 'expense_id' in request.POST:
            expense = get_object_or_404(Expense, expense_id=request.POST['expense_id'])
            if 'delete' in request.POST:
                expense.delete()
            else:
                form = self.form_class(request.POST, instance=expense)
                if form.is_valid():
                    form.instance.user_id = expense.user_id
                    form.save()
                    return redirect(self.get_success_url())
                else:
                    return self.form_invalid(form)
        else:
            form = self.form_class(request.POST)
            if form.is_valid():
                return self.form_valid(form)
            else:
                return self.form_invalid(form)
        return redirect(self.get_success_url())
    

class ShareExpenseGroupView(LoginRequiredMixin, View):
    def post(self, request, *args, **kwargs):
        expense_group = get_object_or_404(ExpenseGroup, group_id=kwargs['group_id'])
        
        form = ExpenseGroupForm(request.POST, instance=expense_group)
        
        if form.is_valid():
            expense_group = form.save()
            print("Form saved successfully with shared_with:", form.cleaned_data['shared_with'])
            return redirect('expenses_mate:expenses_list_create')
        else:
            print("Form errors:", form.errors)
            expenses = expense_group.expense_set.all()
            return render(request, 'expenses_mate/expenses_list.html', {
                'form': form,
                'expense_group': expense_group,
                'expenses': expenses
            })
            

class UpdateExpenseGroupView(LoginRequiredMixin, UpdateView):
    model = ExpenseGroup
    fields = ['title']

    def post(self, request, *args, **kwargs):
        expense_group = get_object_or_404(ExpenseGroup, group_id=kwargs['group_id'])

        expense_group.title = request.POST.get("title")
        expense_group.created_by = request.user

        # shared_with_ids = request.POST.getlist("shared_with")
        # expense_group.shared_with.set(shared_with_ids)

        expense_group.save()

        return redirect(reverse_lazy('expenses_mate:expenses_list_create'))


class UpdateExpenseView(LoginRequiredMixin, UpdateView):
    model = Expense
    fields = ['item_name', 'amount']

    def post(self, request, *args, **kwargs):
        expense = get_object_or_404(Expense, expense_id=kwargs['expense_id'])

        group_id = request.POST.get("group_id")
        expense.item_name = request.POST.get("item_name")
        expense.amount = request.POST.get("amount")

        expense.save()

        return redirect(reverse_lazy('expenses_mate:expense_detail', kwargs={'group_id': group_id}))
    

templates/expenses_mate/expense_list.html
{% extends './layout/base.html' %}

{% block contents %}

<!-- <table class="styled-table">
  <thead>
    <tr>
      <th style="width: 25%;">Username</th>
      <th style="width: 45%;">Title</th>
      <th style="width: 15%;">Badge</th>
      <th style="width: 15%;">Action</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td class="center-content">
        <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-chat/ava1-bg.webp" alt="avatar 1"
          style="width: 45px; height: auto;" alt="Icon" class="table-icon" width="50px">
        <span>Alice Mayer</span>
      </td>
      <td>Title 1</td>
      <td><span class="badge">New</span></td>
      <td><button class="btn-action">Action</button></td>
    </tr>
    <tr>
      <td class="center-content">
        <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-chat/ava2-bg.webp" alt="avatar 1"
          style="width: 45px; height: auto;"  alt="Icon" class="table-icon" width="50px">
        <span>Kate Moss</span>
      </td>
      <td>Title 2</td>
      <td><span class="badge">Update</span></td>
      <td><button class="btn-action">Action</button></td>
    </tr>
    <!- Add more rows as needed 
  </tbody>
</table> -->

<div class="mx-auto w-full md:w-3/4 px-4 mt-1.5">
  <div class="list-input-block">
    <input type="text" id="input__username" class="expenses-list-input" placeholder=" ">
    <label for="input__username" class="floating-label">新しい支出リストを追加</label>
    <span class="border-animation"></span>
    <button class="add-button">+</button>
  </div>

  <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-3 gap-4">
    <div class="card">
      <div class="card-title">
        <span class="badge">New</span>
        <h2 class="title">Card Title</h2>
      </div>
      <div class="user-info">
        <span class="user-name">John Doe</span>
        <span class="user-role">Admin</span>
      </div>
    </div>
    <div class="card">
      <div class="card-title">
        <span class="badge">New</span>
        <h2 class="title">Card Title</h2>
      </div>
      <div class="user-info">
        <span class="user-name">John Doe</span>
        <span class="user-role">Admin</span>
      </div>
    </div>
    <div class="card">
      <div class="card-title">
        <span class="badge">New</span>
        <h2 class="title">Card Title</h2>
      </div>
      <div class="user-info">
        <span class="user-name">John Doe</span>
        <span class="user-role">Admin</span>
      </div>
    </div>
    <div class="card">
      <div class="card-title">
        <span class="badge">New</span>
        <h2 class="title">Card Title</h2>
      </div>
      <div class="user-info">
        <span class="user-name">John Doe</span>
        <span class="user-role">Admin</span>
      </div>
    </div>
    <div class="card">
      <div class="card-title">
        <span class="badge">New</span>
        <h2 class="title">Card Title</h2>
      </div>
      <div class="user-info">
        <span class="user-name">John Doe</span>
        <span class="user-role">Admin</span>
      </div>
    </div>
    <div class="card">
      <div class="card-title">
        <span class="badge">New</span>
        <h2 class="title">Card Title</h2>
      </div>
      <div class="user-info">
        <span class="user-name">John Doe</span>
        <span class="user-role">Admin</span>
      </div>
    </div>
  </div>

</div>



{% endblock %}

templates/expenses_mate/expenses_detail.html
{% extends './layout/base.html' %}
{% load humanize %}
{% load custom_tags %}

{% block contents %}

<div class="container mx-auto p-4">
    <div class="expenses-title">
        <h2 class="flex-1 text-center">{{ expenses_group.title }}</h2>
    </div>

    <form method="post" class="w-full md:w-5/6" style="margin: 0 auto;">
        <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-2 lg:grid-cols-2 gap-4">
            {% csrf_token %}

            <div class="list-input-block grow">
                {{ form.item_name|add_class:"expenses-list-input" }}
                <label for="id_item_name" class="floating-label">アイテム名</label>
                <span class="border-animation"></span>
                {{ form.item_name.errors }}
            </div>

            <div class="grid grid-cols-4 w-full gap-4">
                <div class="grow col-span-3">
                    <div class="list-input-block grow">
                        {% if form.amount %}
                        {{ form.amount|add_class:"expenses-list-input" }}
                        <label for="{{ form.amount.id_for_label }}" class="floating-label">金額</label>
                        <span class="border-animation"></span>
                        {% if form.amount.errors %}
                        <div class="error-list">
                            {{ form.amount.errors }}
                        </div>
                        {% endif %}
                        {% else %}
                        <p class="error-text">Error: The amount field is not available.</p>
                        {% endif %}

                    </div>
                </div>
                <div class="grow-0">
                    <button type="submit" class="add-button">+</button>
                </div>
            </div>
        </div>
    </form>
    <div class="grid grid-cols-1 sm:grid-cols-1 md:grid-cols-3 lg:grid-cols-4">
        <div class="mx-auto p-1 md:p-4 col-span-1 md:col-span-2 lg:col-span-3 mb-4 w-full overflow-visible">
            <h2 class="my-3 expenses-table-title mx-3">支出</h2>
            <table class="expenses-table hidden md:table relative">
                <thead>
                    <tr>
                        <th></th>
                        <th>作成者</th>
                        <th>アイテム名</th>
                        <th>金額</th>
                        <th></th>

                    </tr>
                </thead>
                <tbody>
                    {% for expense in expenses %}
                    <tr>
                        <td class="expenses-table-icon">
                            <i class="fas fa-user-circle"></i>
                        </td>
                        <td>{{ expense.user_id }}</td>
                        <td>{{ expense.item_name }}</td>
                        <td>{{ expense.amount|floatformat:2|intcomma }}</td>
                        <td>
                            <div class="dropdown relative">
                                <div tabindex="0" role="button" class="btn m-1 three-dots">
                                    <i class="fas fa-ellipsis-v"></i>
                                </div>
                                <ul tabindex="0"
                                    class="dropdown-content menu bg-base-100 rounded-box z-50 absolute w-36 p-2 shadow custom-dropdown">
                                    <form method="post"
                                        action="{% url 'expenses_mate:expense_detail' expenses_group.group_id %}">
                                        {% csrf_token %}
                                        <input type="hidden" name="expense_id" value="{{ expense.expense_id }}">
                                        <li>
                                            <button type="submit" name="delete" class="delete-icon">
                                                <i class="fas fa-trash-alt mr-1"></i>
                                                <span class="hidden md:inline">削除</span>
                                            </button>
                                        </li>
                                        <hr />
                                    </form>
                                    <li>
                                        <button class="edit-icon"
                                            onclick="document.getElementById('edit_modal_{{ expense.expense_id }}').showModal()">
                                            <i class="fas fa-edit mr-1"></i>
                                            <span class="hidden md:inline">編集</span>
                                        </button>
                                    </li>
                                </ul>
                            </div>
                        </td>
                    </tr>
                    <dialog id="edit_modal_{{ expense.expense_id }}" class="modal">
                        <div class="modal-box">
                            <form method="dialog">
                                <button class="btn btn-sm btn-circle btn-ghost absolute right-2 top-2">✕</button>
                            </form>
                            <h3 class="text-lg font-semibold mb-3">費用を編集</h3>
                            <form method="POST" action="{% url 'expenses_mate:update_expense' expense.expense_id %}">
                                {% csrf_token %}
                                <input type="hidden" name="group_id" value="{{ expenses_group.group_id }}">
    
                                <div>
                                    <label for="item_name" class="block text-sm font-medium text-gray-700">アイテム名</label>
                                    <div class="mt-2">
                                        <input type="text" id="item_name" name="item_name" value="{{ expense.item_name }}"
                                            class="input input-bordered w-full">
                                    </div>
                                </div>
                                <div>
                                    <label for="amount" class="block text-sm font-medium text-gray-700">金額</label>
                                    <div class="mt-2">
                                        <input type="text" id="amount" name="amount" value="{{ expense.amount }}"
                                            class="input input-bordered w-full">
                                    </div>
                                </div>
    
                                <div class="flex justify-end mt-6">
                                    <button
                                        class="btn bg-gray-300 text-gray-700 px-4 py-2 rounded mr-2 btn-ghost">閉じる</button>
                                    <button type="submit" class="bg-blue-500 text-white px-4 py-2 rounded">編集</button>
                                </div>
                            </form>
                        </div>
                    </dialog>
                    {% endfor %}
                </tbody>
            </table>
            <div class="md:hidden overflow-y-auto">
                {% for expense in expenses %}
                <div
                    class="p-5 shadow-lg rounded-lg min-w-[260px] cursor-pointer transition-shadow duration-300 hover:shadow-xl border my-2 mb-0">
                    <div class="flex justify-between items-center">
                        <div class="expenses-table-icon" style="text-align: left;">
                            <i class="fas fa-user-circle"></i>
                        </div>
                        <div class="dropdown dropdown-bottom dropdown-end relative">
                            <div tabindex="0" role="button" class="btn m-1 three-dots">
                                <i class="fas fa-ellipsis-v"></i>
                            </div>
                            <ul tabindex="0"
                                class="dropdown-content menu bg-base-100 rounded-box z-50 absolute w-36 p-2 shadow custom-dropdown">
                                <form method="post"
                                    action="{% url 'expenses_mate:expense_detail' expenses_group.group_id %}">
                                    {% csrf_token %}
                                    <li>
                                        <input type="hidden" name="expense_id" value="{{ expense.expense_id }}">
                                        <button type="submit" name="delete" class="delete-icon">
                                            <i class="fas fa-trash-alt mr-1"></i>
                                            <span>削除</span>
                                        </button>
                                    </li>
                                    <hr />
                                </form>
                                <li>
                                    <button class="edit-icon"
                                        onclick="document.getElementById('shared_modal_{{ expense.expense_id }}').showModal()">
                                        <i class="fas fa-edit mr-1"></i>
                                        <span>編集</span>
                                    </button>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <h3 class="text-darkmagenta text-xl font-semibold mt-3">{{ expense.user_id }}</h3>
                    <p class="leading-6 my-3">アイテム名: <span class="font-bold">{{ expense.item_name }}</span></p>
                    <p class="leading-6">金額: <span class="font-bold">{{ expense.amount|floatformat:2|intcomma }}</span>
                    </p>
                    <dialog id="edit_modal_{{ expense.expense_id }}" class="modal">
                        <div class="modal-box">
                            <form method="dialog">
                                <button class="btn btn-sm btn-circle btn-ghost absolute right-2 top-2">✕</button>
                            </form>
                            <h3 class="text-lg font-semibold mb-3">費用を編集</h3>
                            <form method="POST" action="{% url 'expenses_mate:update_expense' expense.expense_id %}">
                                {% csrf_token %}
                                <input type="hidden" name="group_id" value="{{ expenses_group.group_id }}">
    
                                <div>
                                    <label for="item_name" class="block text-sm font-medium text-gray-700">アイテム名</label>
                                    <div class="mt-2">
                                        <input type="text" id="item_name" name="item_name" value="{{ expense.item_name }}"
                                            class="input input-bordered w-full">
                                    </div>
                                </div>
                                <div>
                                    <label for="amount" class="block text-sm font-medium text-gray-700">金額</label>
                                    <div class="mt-2">
                                        <input type="text" id="amount" name="amount" value="{{ expense.amount }}"
                                            class="input input-bordered w-full">
                                    </div>
                                </div>
    
                                <div class="flex justify-end mt-6">
                                    <button
                                        class="btn bg-gray-300 text-gray-700 px-4 py-2 rounded mr-2 btn-ghost">閉じる</button>
                                    <button type="submit" class="bg-blue-500 text-white px-4 py-2 rounded">編集</button>
                                </div>
                            </form>
                        </div>
                    </dialog>
                </div>
                {% endfor %}
            </div>
        </div>
        <div class="container mx-auto p-4 lg:p-8 my-4 w-full">
            <h2 class="text-2xl font-semibold text-center expenses-user-info-title my-4">ユーザーごとの合計金額</h2>
            <div class="max-w-lg mx-auto mt-5 p-4 border border-gray-200 rounded-lg shadow-md bg-white">
                {% for user_total in user_totals %}
                <div class="flex justify-between py-2 border-b border-gray-200">
                    <span class="text-lg font-bold text-gray-800">
                        {{ user_total.user_id__username }}：
                    </span>
                    <span class="text-lg font-bold text-blue-600">
                        {{ user_total.total_amount }}
                    </span>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>

{% endblock %}